inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'test/fixtures/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'log/**/*'
    - 'tmp/**/*'

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Lint/UnusedMethodArgument:
  Enabled: false

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Layout/AlignArray:
  Enabled: false

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  Exclude:
    - 'config/initializers/*'

Style/BracesAroundHashParameters:
  Enabled: false

Style/ExpandPathArguments:
  Exclude:
    - 'spec/rails_helper.rb'

Layout/CaseIndentation:
  EnforcedStyle: end

Layout/ClosingParenthesisIndentation:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/IndentHash:
  EnforcedStyle: consistent

Style/IfUnlessModifier:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/RescueModifier:
  Enabled: true

# This is the rule that enforces single quotes.
Style/StringLiterals:
  Enabled: false

Style/WordArray:
  Enabled: false

Metrics/ModuleLength:
  Max: 250

Metrics/BlockLength:
  ExcludedMethods:
    - context
    - describe
    - it
    - shared_examples
    - shared_examples_for
    - namespace
    - draw
