default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: metafield_sync_dev

test:
  <<: *default
  database: metafield_sync_test

production:
  <<: *default
  database: metafield_sync_production
  pool: 20
  timeout: 5000
